name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npx tsc --noEmit

      - name: Lint
        run: npm run lint

      - name: Format check
        run: npx prettier --check .

      - name: Run tests
        run: npm run test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          directory: ./coverage/
          fail_ci_if_error: false

      - name: Build
        run: npm run build

      - name: Cache validation
        run: |
          if [ -f ".next/cache" ]; then
            echo "Next.js cache exists ✅"
          else
            echo "Next.js cache missing ❌"
            exit 1
          fi

      - name: Bundle analysis
        run: npm run analyze
        env:
          ANALYZE: true

      - name: Send Slack Notification
        if: always()
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "text": "*CI実行結果*",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*${{ github.repository }}* のCI結果:\n${{ job.status == 'success' && '✅ すべてのチェックが通過しました' || '❌ いくつかのチェックが失敗しました' }}"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*ブランチ:*\n${{ github.ref_name }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*コミット:*\n${{ github.sha }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*テスト結果:*\n${{ job.status == 'success' && '✅ 成功' || '❌ 失敗' }}"
                    }
                  ]
                }
              ]
            }
